### ISSUE TITLE
New webpack produces -> Error: Content and Map of this Source is no longer available (only size() is supported)

### ISSUE THREAD

**Issue by jmesa-sistel** [euclid1990/write-assets-webpack-plugin#4]
Hello

I'm using new webpack-dev-server@3.1.14 because angular has updated to this version.
When I try to use your plugin I get an error:
> Error: Content and Map of this Source is no longer available (only size() is supported)

This is because webpack devs have changed the assets behaviour: 
[add a new version of emitting assets which allows to free memory](https://github.com/webpack/webpack/pull/8642)
Can you fix your great plugin?

**Comment by jmesa-sistel** [comment]
@euclid1990 Any news?

**Comment by euclid1990** [comment]
@jmesa-sistel I will fix it after Vietnam Lunar New Year holidays. Thank for reporting

**Comment by jmesa-sistel** [comment]
@euclid1990 After read the [comments](https://github.com/webpack/webpack/pull/8642#issuecomment-455342804) I think it has no solution. Web dev server has the same problem with [writeToDisk ](https://github.com/webpack/webpack/pull/8642#issuecomment-455758117)  and the answer is not use [writeToDisk option](https://webpack.js.org/configuration/dev-server/#devserver-writetodisk-)

**Comment by euclid1990** [comment]
@jmesa-sistel now I have no idea for this problem because I am not have any Laptop and PC near me. I will inspect it after my holidays and reply you asap :(

**Comment by jmesa-sistel** [comment]
@euclid1990 
Did you closed because you don't know how to fix it? Or because there is no fix?

**Comment by euclid1990** [comment]
@jmesa-sistel Sorry, I can't reproduce your error. However, I've been updated the new `webpack/lib` versions, everything is running smoothly, you can try it now!
https://www.npmjs.com/package/write-assets-webpack-plugin `v1.0.5`
